#POST http://127.0.0.1:8000/teacher/leave/all
#Content-Type: application/json
##
##{
##  "id": "3"
##}
#
###
POST http://127.0.0.1:8000/teacher/add
Content-Type: application/json

{
  "id": "2",
  "name": "素强"
}

###
POST http://127.0.0.1:8000/student/leave
Content-Type: application/json

{
  "id": "2",
  "reason": "生病"
}


###
POST http://127.0.0.1:8000/teacher/leave/true
Content-Type: application/json

{
  "id": "1"
}

###
POST http://127.0.0.1:8000/teacher/attendance_all
Content-Type: application/json